name: CI Test Cases

on:
  push:
    branches:
      - feat-action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libpangocairo-1.0-0 \
            libpangoft2-1.0-0 \
            libgtk-3-0 \
            fonts-liberation \
            libappindicator3-1 \
            xdg-utils \
            libgbm1 \
            xvfb

      - name: Setup Browser
        uses: browser-actions/setup-chrome@v1 
        with:
          chrome-version: 120
          install-chromedriver: true
      - run: chrome --version
        
      - name: Maven Install
        working-directory: test-framework
        run: mvn clean install -DskipTests=true
        
      - name: Run Selenium Tests with Maven
        working-directory: test-framework
        env:
          DISPLAY: ':99'
        run: |
          # Start a virtual display for headless Chrome
          Xvfb :99 -screen 0 1920x1080x24 & 
          # Run tests
          mvn test

  notify:
    needs: test
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify Microsoft Teams
        run: |
          curl -H 'Content-Type: application/json' \
               -d '{"@type": "MessageCard", "@context": "http://schema.org/extensions", "summary": "Workflow Failure", "themeColor": "FF0000", "title": "CI Tests have failed", "text": "CI Tests workflow has encountered an error. Please check the logs for more details."}' \
               ${{ secrets.TEAMS_WEBHOOK }}
               
