name: CI Test Cases

on:
  push:
    branches:
      - workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libnss3 \
            libgconf-2-4 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libpangocairo-1.0-0 \
            libpangoft2-1.0-0 \
            libgtk-3-0 \
            fonts-liberation \
            libappindicator3-1 \
            xdg-utils

      - name: Setup Browser
        uses: browser-actions/setup-chrome@latest 
      - run: chrome --version
        
      - name: Maven Install
        working-directory: test-framework
        run: mvn clean install -DskipTests=true
        
      - name: Build with Maven
        working-directory: test-framework
        env:
          DISPLAY: ':99'
        run: |
          mvn test
